[package]
name = "actix-jwt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "8.1.1"
chrono = "0.4.22"
actix-web = "4.2.1"
serde = "1.0.145"
futures = "0.3.24"
futures-util = "0.3.24"